"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

import os 

APP = ["sourceCode.py"]
DATA_FILES = ["image", "sound"]
OPTIONS = {'argv_emulation': True,}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
